# Generated by Django 4.2.7 on 2024-06-02 00:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="student",
            name="phonenumber",
            field=models.CharField(max_length=15),
        ),
    ]
